
const BUY = "BUY";
const SELL = "SELL";
const USD = "USD";
const EUR = "EUR";
const BYN = "BYN";
const BUY_USD = `${BUY}_${USD}`;
const BUY_EUR = `${BUY}_${EUR}`;
const SELL_USD = `${SELL}_${USD}`;
const SELL_EUR = `${SELL}_${EUR}`;
const MINSK = "MINSK";
const GRODNO = "GRODNO";
const BOBRUYSK = "BOBRUYSK";
const BARANOVICHI = "BARANOVICHI";
const LIST_OFFERS = 'LIST_OFFERS';
const LIST_POTENTIAL_MATCHES = 'LIST_POTENTIAL_MATCHES';

export {BUY, SELL, USD, EUR, BYN, BUY_USD, BUY_EUR, SELL_USD, SELL_EUR, MINSK, GRODNO, BOBRUYSK, BARANOVICHI,
  LIST_OFFERS, LIST_POTENTIAL_MATCHES}
